### ISSUE TITLE
Page doesn't load when in production mode

### ISSUE THREAD

**Issue by stasyaner** [webdeb/next-styles#3]
Hello again :) Thank you for you support.
I faced a strange issue when deployed my next.js app in production mode (npm run build; npm start).
The page where I imported my css-module is not loading. And I can't understand why.
If I comment the import line and the style, it works fine.
Also not moduled styles do import fine and don't break anything.
Do you have any ideas?
Thanks a lot.

**Comment by webdeb** [comment]
No, I don't have any ideas. It could be anything.  If you want me to try and help, please create a minimal example `npx create-next-app next-styles-bug` & try to replicate the problem there.

**Comment by stasyaner** [comment]
Thank you for your help.
Please find the repo with replication [here](https://github.com/stasyaner/next-styles-bug).
There it's not working even in development mode.
There are 2 pages: index and bugpage.
Index page has link to bugpage:
```html
<p className="description">
        To see the bug <Link href='/bugpage'><a>follow here</a></Link>.
</p>
```
If you follow it, bugpage won't load. But you can directly go to localhost:3322/bugpage and it will load and if you go back to home page the link will be working.
Thanks.

**Comment by webdeb** [comment]
@stasyaner thanks for reporting this and creating an example, the issue is the same this one:
https://github.com/zeit/next-plugins/issues/282 because the internals of `next-styles` are built the same way like `next-css`. The workaround which worked is simple.

create a global.scss file: in `style/global.scss` (it can be even empty, just to trigger the loaders..)

and load it inside `pages/_app.js`
```
import "../style/global.scss"
export default function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}
```

Please check if it works for you

**Comment by stasyaner** [comment]
Wow. It works. Thanks a lot for you help!
