### ISSUE TITLE
[Feature request] leverage global scss variables import

### ISSUE THREAD

**Issue by yuri-scarbaci-lenio** [webdeb/next-styles#8]
Based on the problem [described here](https://github.com/zeit/next-plugins/issues/475#issuecomment-526485323)

would be really great if we could do something like
```
const withStyles = require('@webdeb/next-styles')
module.exports = withStyles({
    sass: true,
    sassLoaderOptions: {
        resources: ["./styles/colors.scss"]
    }
})
```
and have next-styles auto-magically handle that for us

**Comment by webdeb** [comment]
Hmm, to be honest, I personally don't like this auto-magically approach.
Since we can define `includePaths: ["src/styles"]` it's easy enough to import the stuff you need without knowing the relative path. But do it explicitly instead.

```
@import "variables" ;
@import "colors";

...
```

So I would't encourage people to go the implicit way.

At the other hand, I think, that it might make sense to just allow additional `loaders`, which you are free to add independently.

**Comment by yuri-scarbaci-lenio** [comment]
Well that's true, 
 guess we better keep it as explicit as possible to avoid unwanted edge-cases and further problems,

Guess the only advantage would be not having to import tens of file if one has that many, but on the other end it could be also worked around by defining a single entrypoint scss that imports the tens of other files and import the single scss...

Okay I'm convinced, thanks for taking the time to answer, I will close this issue.
